"""
Django settings for mebshop project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'nn+m+a0l21w!1t+1wfk37x-_aaera@@dkibr)q4q#mq-fphg4_'

# GOOGLE_RECAPTCHA_SECRET_KEY

RECAPTCHA_PUBLIC_KEY = '6Ld8E7YUAAAAAFQ6HO4lRz5YmVAsVW4vme6mlJx3'
RECAPTCHA_PRIVATE_KEY = '6Ld8E7YUAAAAAPj--aLxdQr88cTN92tmd1wTXh16'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition
CRISPY_TEMPLATE_PACK = 'bootstrap3'
INSTALLED_APPS = [

     'metatags',
    # pip install https://github.com/darklow/django-suit/tarball/v2
    # добавим suit-admin
    'mebshop.apps.SuitConfig',

    'django.contrib.admin',
    # pip install django-admin-list-filter-dropdown
    'django_admin_listfilter_dropdown',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'ckeditor',
    'ckeditor_uploader',
    'mptt',
    'transliterate',
    'snowpenguin.django.recaptcha2',
    # pip install django-debug-toolbar
    'debug_toolbar',
    # ----------
    'homepage',
    'orders',
    'filters',
    'properties',
    'products',
    'contact',
    'delivery',
    'underorder',
    'more_itertools',
    # 'django_elasticsearch_dsl',
    # pip install django-crispy-forms
    'crispy_forms',
    # для удаления фото
    'django_cleanup',
]
ELASTICSEARCH_DSL={
    'default': {
        'hosts': 'http://127.0.0.1:9200/'
    },
}

INTERNAL_IPS = [
    # ...
    '127.0.0.1',
    # ...
]
MIDDLEWARE = [
    # debugToolbar
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mebshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
        # add template path
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                 # выводим инфу на всех страницах
                'products.context_processors.getting_category',
                'orders.context_processors.getting_basket_info',
                # grappelli
                # 'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'mebshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Отправка почты
# EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_HOST_USER = 'sergik111'
# EMAIL_HOST_PASSWORD = '1tek-shop@mail.ru'
# EMAIL_PORT =  587
# EMAIL_USE_TLS = True
# EMAIL_HOST_SSL = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
# ---------------1 static-----------
STATIC_URL = '/static/'

# add static path
STATIC_DIRS = 'static'

STATICFILES_DIRS = [
    STATIC_DIRS,
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# ---------------2 static-----------
# STATIC_URL = '/static/'
# STATICFILES_DIRS = (
#   os.path.join(BASE_DIR, "static"),
# )
# STATIC_ROOT = os.path.join(BASE_DIR, "static/", "static_prod")
#
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, "static", "media")

# ----------------ckeditor-----------
# CKEDITOR_CONFIGS = {
#     'default': {
#         'width': '100%',
#         'height': 600,
#         'toolbar': 'Custom',
#         'extraPlugins': ','.join(['codesnippet', 'youtube']),
#         'toolbar_Custom': [
#             ['Bold', 'Italic', 'Underline'],
#             ['Font', 'FontSize','TextColor', 'BGColor'],
#             ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
#             ['Link', 'Unlink'],
#             ['RemoveFormat', 'Source','CodeSnippet', 'Image', 'Youtube']
#         ],
#
#     },
# }
# -----------------------2----------------
# Настройки ckeitor

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default':{
        'toolbar': 'None',
 'height': 200,
 'width': 800,
 'extraPlugins':'codesnippet',
    },
}

CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js'
CKEDITOR_IMAGE_BACKEND = 'pillow'

CKEDITOR_UPLOAD_SLUGIFY_FILENAME = False
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_BROWSE_SHOW_DIRS = True
