# Generated by Django 2.2.4 on 2019-09-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0020_auto_20190922_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, default='', max_length=250)),
                ('name', models.CharField(default='', max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtercategories', to='products.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Filter Category',
                'verbose_name_plural': 'Filters Category',
            },
        ),
        migrations.CreateModel(
            name='FilterSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, default='', max_length=250)),
                ('url', models.CharField(blank=True, default='', max_length=250)),
                ('name', models.CharField(default='', max_length=250)),
                ('filter_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filterselect', to='filters.FilterCategory', verbose_name='Filter Category')),
            ],
            options={
                'verbose_name': 'Filter Select',
                'verbose_name_plural': 'Filters Select',
            },
        ),
        migrations.CreateModel(
            name='ProductFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_select_product', to='filters.FilterCategory', verbose_name='Filter Category')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filterproducts', to='products.Product', verbose_name='Product')),
                ('values', models.ManyToManyField(blank=True, related_name='filtervalues', to='filters.FilterSelect', verbose_name='Values')),
            ],
            options={
                'verbose_name': 'Product Filter',
                'verbose_name_plural': 'Product Filters',
            },
        ),
    ]
