# Generated by Django 2.2.4 on 2019-09-22 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0004_auto_20190923_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilter',
            name='product',
            field=models.ForeignKey(db_column='product_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filterproducts', to='products.Product', verbose_name='Product'),
        ),
    ]
