# Generated by Django 2.2.4 on 2019-09-22 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0005_auto_20190923_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtercategory',
            name='category',
            field=models.ForeignKey(db_column='category_name', on_delete=django.db.models.deletion.CASCADE, related_name='filtercategories', to='products.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='productfilter',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filterproducts', to='products.Product', verbose_name='Product'),
        ),
    ]
