# Generated by Django 2.2.4 on 2019-09-22 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0006_auto_20190923_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filterselect',
            old_name='name',
            new_name='names',
        ),
        migrations.AlterField(
            model_name='filterselect',
            name='filter_category',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, related_name='filterselect', to='filters.FilterCategory', verbose_name='Filter Category'),
        ),
    ]
