# Generated by Django 2.2.4 on 2019-09-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0008_auto_20190923_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filterselect',
            old_name='names',
            new_name='name',
        ),
    ]
