# Generated by Django 2.2.4 on 2019-09-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0013_auto_20190924_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtercategory',
            name='name',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
