# Generated by Django 2.2.4 on 2019-09-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0014_auto_20190924_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilter',
            name='filter_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_select_product', to='filters.FilterCategory', to_field='name', verbose_name='Filter Category'),
        ),
    ]
