# Generated by Django 2.2.4 on 2019-09-24 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0016_remove_productfilter_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilter',
            name='values',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filtervalues', to='filters.FilterSelect', verbose_name='Values'),
        ),
    ]
