# Generated by Django 2.2.4 on 2019-09-24 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0018_auto_20190925_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilter',
            name='values',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filtervalues', to='filters.FilterSelect', to_field='name', verbose_name='Values'),
        ),
    ]
