# Generated by Django 2.2.4 on 2019-09-26 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20190922_1948'),
        ('filters', '0020_auto_20190926_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterselect',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='Category'),
        ),
    ]
