# Generated by Django 2.2.4 on 2019-09-27 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0022_auto_20190926_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterselect',
            name='category',
        ),
        migrations.AlterField(
            model_name='filtercategory',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='filterselect',
            name='filter_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filters.FilterCategory', verbose_name='Filter Category'),
        ),
        migrations.AlterField(
            model_name='filterselect',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='productfilter',
            name='filter_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_select_product', to='filters.FilterCategory', verbose_name='Filter Category'),
        ),
        migrations.RemoveField(
            model_name='productfilter',
            name='values',
        ),
        migrations.AddField(
            model_name='productfilter',
            name='values',
            field=models.ManyToManyField(blank=True, related_name='filtervalues', to='filters.FilterSelect', verbose_name='Values'),
        ),
    ]
