# Generated by Django 2.2.4 on 2019-09-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0023_auto_20190928_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtercategory',
            name='name',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='filterselect',
            name='filter_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filters.FilterCategory', to_field='name', verbose_name='Filter Category'),
        ),
    ]
