# Generated by Django 2.2.4 on 2019-09-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0024_auto_20190928_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtercategory',
            name='name',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='productfilter',
            name='filter_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_select_product', to='filters.FilterCategory', to_field='name', verbose_name='Filter Category'),
        ),
    ]
