# Generated by Django 2.2.4 on 2019-09-28 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20190922_1948'),
        ('filters', '0026_auto_20190928_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterselect',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
    ]
