# Generated by Django 2.2.4 on 2019-09-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0027_filterselect_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterselect',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category', to_field='name', verbose_name='Категория'),
        ),
    ]
