# Generated by Django 2.2.4 on 2019-10-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0028_auto_20190928_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfilter',
            name='values',
        ),
        migrations.AddField(
            model_name='productfilter',
            name='values',
            field=models.ManyToManyField(blank=True, null=True, related_name='filtervalues', to='filters.FilterSelect', verbose_name='Values'),
        ),
    ]
