# Generated by Django 2.2.4 on 2019-10-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0029_auto_20191012_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilter',
            name='values',
            field=models.ManyToManyField(blank=True, related_name='filtervalues', to='filters.FilterSelect', verbose_name='Values'),
        ),
    ]
