# Generated by Django 2.2.4 on 2019-10-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0030_auto_20191012_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfilter',
            name='values',
        ),
        migrations.AddField(
            model_name='productfilter',
            name='values',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filtervalues', to='filters.FilterSelect', to_field='name', verbose_name='Values'),
        ),
    ]
