# Generated by Django 2.2.4 on 2019-11-16 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0031_auto_20191012_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtercategory',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='filterselect',
            name='filter_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filters.FilterCategory', verbose_name='Filter Category'),
        ),
        migrations.AlterField(
            model_name='filterselect',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='productfilter',
            name='filter_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_select_product', to='filters.FilterCategory', verbose_name='Filter Category'),
        ),
        migrations.AlterField(
            model_name='productfilter',
            name='values',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filtervalues', to='filters.FilterSelect', verbose_name='Values'),
        ),
    ]
