# Generated by Django 2.2.4 on 2019-11-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0033_filterselect_simple'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilter',
            name='simple',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
