# Generated by Django 2.2.4 on 2019-11-09 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20191109_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='category_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_property', to='properties.CategoryProperty', to_field='name', verbose_name='Propery'),
        ),
    ]
