# Generated by Django 2.2.4 on 2019-11-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20191109_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproperty',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250, null=True, unique=True),
        ),
    ]
