# Generated by Django 2.2.4 on 2019-11-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20191109_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproperty',
            name='name',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
