# Generated by Django 2.2.4 on 2019-08-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='session_key',
            new_name='token',
        ),
    ]
