# Generated by Django 2.2.4 on 2019-08-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190830_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
