# Generated by Django 2.2.4 on 2019-08-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190830_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
