# Generated by Django 2.2.4 on 2019-09-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190911_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_surname',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
