# Generated by Django 2.2.4 on 2019-09-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190901_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
