# Generated by Django 2.2.4 on 2019-09-01 11:57

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=products.models.image_gallary_folder),
        ),
    ]
