# Generated by Django 2.2.4 on 2019-09-03 15:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190902_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brend',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Brend', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categ',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='products.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_short',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='Текст(короткий)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=products.models.image_folder, verbose_name='Фотка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_product',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_old',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True, verbose_name='SLUG(Не трогать)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='top',
            field=models.BooleanField(default=False, verbose_name='В топе(на гл.странице)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
    ]
