# Generated by Django 2.2.4 on 2019-09-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190903_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slider',
            field=models.BooleanField(default=False, verbose_name='Слайдер(на гл.странице)'),
        ),
    ]
