# Generated by Django 2.2.4 on 2019-09-14 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190914_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ForeignKey(blank=True, default=None, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Attributs', verbose_name='Атрибут'),
        ),
    ]
