# Generated by Django 2.2.4 on 2019-09-19 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190914_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributs',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='attributs',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='attributs',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True, verbose_name='Транслит'),
        ),
        migrations.AlterField(
            model_name='brend',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True, verbose_name='Транслит'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True, verbose_name='Транслит(Не трогать)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True, verbose_name='Транслит'),
        ),
    ]
