# Generated by Django 2.2.4 on 2019-09-22 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190919_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Название')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Размер(глубина)',
                'verbose_name_plural': 'Размер(глубина)',
            },
        ),
    ]
