# Generated by Django 2.2.4 on 2019-09-22 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_deep'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deep',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Deep', verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Attributs', verbose_name='Подкатегория'),
        ),
    ]
