# Generated by Django 2.2.4 on 2019-09-22 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190922_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributs',
            name='category',
        ),
        migrations.RemoveField(
            model_name='attributs',
            name='name',
        ),
        migrations.RemoveField(
            model_name='attributs',
            name='slug',
        ),
        migrations.AddField(
            model_name='attributs',
            name='Deep',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Deep', verbose_name='ПодКатегория'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, default=None, null=True, verbose_name='Транслит')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегория',
            },
        ),
        migrations.AddField(
            model_name='attributs',
            name='Subcategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Subcategory', verbose_name='ПодКатегория'),
        ),
    ]
