# Generated by Django 2.2.4 on 2019-09-22 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20190922_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributs',
            name='Deep',
        ),
        migrations.RemoveField(
            model_name='attributs',
            name='Subcategory',
        ),
        migrations.AddField(
            model_name='attributs',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='attributs',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='attributs',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True, verbose_name='Транслит'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
