# Generated by Django 2.2.4 on 2019-09-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20190922_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributs',
            name='deep',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Глубина'),
        ),
        migrations.AddField(
            model_name='attributs',
            name='height',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='attributs',
            name='width',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='attributs',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название'),
        ),
    ]
