# Generated by Django 2.2.4 on 2019-09-22 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20190922_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributs',
            name='height',
        ),
        migrations.RemoveField(
            model_name='attributs',
            name='width',
        ),
        migrations.AlterField(
            model_name='attributs',
            name='deep',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Deep', verbose_name='Категория'),
        ),
    ]
