# Generated by Django 2.2.4 on 2019-09-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20190922_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deep',
            name='category',
        ),
        migrations.AlterField(
            model_name='deep',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Глубина'),
        ),
    ]
