# Generated by Django 2.2.4 on 2019-10-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20190922_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Название'),
        ),
    ]
